version: '3.8'

services:
  vkspam_frontend_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - vkspam
    container_name: vue3-app
    restart: unless-stopped
networks:
  vkspam:
    external: true